### ISSUE TITLE
Rename tsconfig to tsConfig

### ISSUE THREAD

**Issue by ppa-pawe** [thinktecture/nodejs-vnext-webapi#8]
"npm run watch" fails (on linux) due to naming mismatch

**Comment by ManuelRauber** [comment]
Do you have an exact error message for me? :)

**Comment by ManuelRauber** [comment]
Ah, nevermind. Should read the title. ;)

**Comment by ManuelRauber** [comment]
Renamed

**Comment by ppa-pawe** [comment]
works like a charm :)
